services:  
 web:  
   image: vote-apache-teglia
   ports:  
     - "8087:80"  
   depends_on:  
     - db  
  
 db:  
   image: vote-mysql-teglia
   environment:  
     MYSQL_ROOT_PASSWORD: P@ssw0rdEN24
